"""Add user id's to prios and todos

Revision ID: 56115a41f346
Revises: 08bcd51bd84d
Create Date: 2025-08-11 10:22:11.599076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56115a41f346'
down_revision: Union[str, Sequence[str], None] = '08bcd51bd84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priorities', sa.Column('user_key', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'priorities', 'users', ['user_key'], ['key'])
    op.add_column('todos', sa.Column('user_key', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'todos', 'users', ['user_key'], ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'user_key')
    op.drop_constraint(None, 'priorities', type_='foreignkey')
    op.drop_column('priorities', 'user_key')
    # ### end Alembic commands ###
