"""Add indexes and constraints

Revision ID: 5d6d1a567918
Revises: 56115a41f346
Create Date: 2025-08-11 10:25:53.881138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6d1a567918'
down_revision: Union[str, Sequence[str], None] = '56115a41f346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_priority_user_key', 'priorities', ['user_key'], unique=False)
    op.create_unique_constraint('uq_priority_user_name', 'priorities', ['user_key', 'name'])
    op.create_unique_constraint('uq_priority_user_order', 'priorities', ['user_key', 'order'])
    op.create_index('ix_todo_user_key', 'todos', ['user_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todo_user_key', table_name='todos')
    op.drop_constraint('uq_priority_user_order', 'priorities', type_='unique')
    op.drop_constraint('uq_priority_user_name', 'priorities', type_='unique')
    op.drop_index('ix_priority_user_key', table_name='priorities')
    # ### end Alembic commands ###
