"""Fix migrations oopsie

Revision ID: b4237f6c32a0
Revises: c924bffa2328
Create Date: 2025-08-21 10:28:28.674130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4237f6c32a0"
down_revision: Union[str, Sequence[str], None] = "c924bffa2328"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("user_key", sa.String(length=36), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=36), nullable=False),
        sa.Column("icon", sa.String(length=36), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statuses")),
        sa.UniqueConstraint("key", name=op.f("uq_statuses_key")),
    )
    # Update todos add status
    op.add_column("todos", sa.Column("status", sa.String(length=36), nullable=True))
    op.create_index(
        "ix_todo_user_key_status", "todos", ["user_key", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todos_id"), table_name="todos")
    op.drop_index("ix_todo_user_key_status", table_name="todos")
    op.drop_index("ix_todo_user_key_priority", table_name="todos")
    op.drop_index("ix_todo_user_key_key", table_name="todos")
    op.drop_index("ix_todo_user_key_completed", table_name="todos")
    op.drop_index("ix_todo_user_key", table_name="todos")
    op.drop_index("ix_todo_priority", table_name="todos")
    op.drop_index("ix_todo_completed", table_name="todos")
    op.drop_table("todos")
    op.drop_index("ix_priority_user_key_key", table_name="priorities")
    op.drop_index("ix_priority_user_key", table_name="priorities")
    op.drop_index(op.f("ix_priorities_id"), table_name="priorities")
    op.drop_table("priorities")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index("ix_user_key", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_statuses_id"), table_name="statuses")
    op.drop_table("statuses")
    # ### end Alembic commands ###
