"""Change priority column to string

Revision ID: c25d25f0e451
Revises: 5d31a3788a8a
Create Date: 2025-08-07 11:42:35.655528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c25d25f0e451'
down_revision: Union[str, Sequence[str], None] = '5d31a3788a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'priority',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               nullable=False)
    op.create_foreign_key(None, 'todos', 'priorities', ['priority'], ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.alter_column('todos', 'priority',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
