"""Add icon column to priorities

Revision ID: e74892fba37b
Revises: c25d25f0e451
Create Date: 2025-08-07 16:39:13.313367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74892fba37b'
down_revision: Union[str, Sequence[str], None] = 'c25d25f0e451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priorities', sa.Column('icon', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priorities', 'icon')
    # ### end Alembic commands ###
